### ISSUE TITLE
`rocks albedos` and `rocks taxonomies` miss information

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#24]
Hi Max,

Today I noticed that `rocks albedos` and `rocks taxonomies` in plural are missing some information in comparison to `rocks albedo` and `rocks taxonomy` which led to some confusion on my end.

If there is data available I would expect the plural forms of the commands to also find it.

Albedo example:
```
$ rocks albedos 2010 TH19
No albedos on record for (499582) 2010 TH19.
$ rocks albedo 2010 TH19 
0.052 +- 0.032 
```

And for spectra:
```
$ rocks taxonomies 2005 EC224 
No taxonomies on record for (175189) 2005 EC224.
$ rocks taxonomy 2005 EC224 
Q
```

Cheers,
Lauri

**Comment by maxmahlke** [comment]
Hi Lauri, apologies for the delay. This was most certainly an error on the side of SsODNet (empty query responses) which was fixed with the latest update. The commands return the expected output on my side now. Thanks for reporting!
