### ISSUE TITLE
`ŗocks taxonomies` misses data

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#26]
Hi,

Reminiscent of #24, for some asteroids running `rocks taxonomies` again comes up with no results while `rocks taxonomy` works as expected. I suppose it is likely to again be on the SsODNet side?

Example case:
```
$ rocks taxonomies 2011 CG2
No taxonomies on record for (None) 2011 CG2.
$ rocks taxonomy 2011 CG2 
X
```

This is with rocks 1.8,9.

Thanks!

**Comment by maxmahlke** [comment]
Hi Lauri, yes this is a datacloud issue that we're working on. You can check if it's `rocks` or SsODNet using

```$ rocks taxonomy.links 2011cg2```

which gives you the link to the relevant datacloud json file. In this case, it says `data:null`.

I'll leave the issue open until we pushed the fixed datacloud version.

**Comment by maxmahlke** [comment]
Issue in datacloud is fixed.
