### ISSUE TITLE
Warning reading `colors` datacloud

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#30]
Hi Max,

This is a lower priority thing, but I wanted to report that fetching the colors datacloud for an asteroid that doesn't actually have colors in SsODNet results in warnings from pydantic. This is with space-rocks 1.9.3.

Example output from the Python interpreter:

```
>>> ast2 = Rock("2011 AA37", datacloud=["colors"])
/usr/lib/python3.11/site-packages/pydantic/main.py:314: UserWarning: Pydantic serializer warnings:
  Expected `float` but got `str` - serialized value may not be as expected
  Expected `float` but got `str` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
```

**Comment by maxmahlke** [comment]
Hi Lauri, thanks for letting me know. I'm currently going through a long list of minor fixes, I added this item.

**Comment by maxmahlke** [comment]
Hi Lauri, I'm not seeing the warning on my side, I might have fixed it passively when doing revisions in the past weeks. Could you check whether it still occurs with version 1.9.6 (published yesterday)?

**Comment by Siltala** [comment]
Hi, I was able to reproduce with rocks 1.9.7. 
Since you can't reproduce I figured I would try clearing rocks's cache directory. With that, the issue disappeared and all seems fine.

Closing, thanks!
