### ISSUE TITLE
Outdated bft documentation

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#33]
Hi Max,

As a more trivial thing, I noticed that the documentation for the default bft columns at https://rocks.readthedocs.io/en/latest/appendix.html#lite-columns is a little outdated; it refers to `orbital_elements.perihelion_distance.value` but the field name has been changed to `orbital_elements.periapsis_distance.value` since that was written. It confused me for a few minutes when I was trying to access this field, but it was easy enough to figure out :)

**Comment by maxmahlke** [comment]
I could have sworn that I corrected that. Thanks! How about you submit a PR so you finally get your well-deserved "Collaborator" status for `rocks`? The file to correct is `docs/appendix.rst`.
