### ISSUE TITLE
Pydantic warning with `rocks colors 1998 KG3`

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#38]
Hi Max, 

Running rocks 1.9.8, I noticed that looking up colors for this specific asteroid leads to a warning. It doesn't crash so this is also lower priority, but I report it just in case.

```
$ rocks colors 1998 KG3 
/usr/lib/python3.11/site-packages/pydantic/main.py:328: UserWarning: Pydantic serializer warnings:
  Expected `float` but got `str` - serialized value may not be as expected
  Expected `float` but got `str` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
No colors on record for 1998 KG3.
```

**Comment by Siltala** [comment]
This rang a few bells so I checked and it actually looks a lot like #30 which was previously fixed. I confirm that in this case resetting the cache makes no difference though

**Comment by maxmahlke** [comment]
Ah yes, the bug that vanished and now reappeared. Thanks! It was just a matter of wrong default types. Will be fixed in the next release.
