### ISSUE TITLE
Error codes from CLI

### ISSUE THREAD

**Issue by ysBach** [maxmahlke/rocks#4]
Hi! I happened to encounter this repo from one of recent publications on arXiv.
I find this tool can be extremely powerful and useful for solar-system scientists.

When trying tutorials, although it works, I see some annoying errors:

```
❯ rocks class Eos

Eos:
Error: parameters -> physical -> density -> method is invalid: value is not a valid list
Passed value: {'name': 'Computed', 'shortbib': 'berthier+2022', 'source': 'TBD', 'title': 'SsODNet paper', 'year': 2022, 'bibcode': 'TBD'}
Replacing value with empty default to continue.

Error: parameters -> physical -> density -> bibref is invalid: value is not a valid list
Passed value: {'shortbib': 'berthier+2022', 'title': 'SsODNet paper', 'year': 2022, 'bibcode': 'TBD', 'doi': 'TBD'}
Replacing value with empty default to continue.

Error: parameters -> dynamical -> tisserand_parameter -> method is invalid: value is not a valid list
Passed value: {'name': 'Computed', 'shortbib': 'berthier+2022', 'source': 'TBD', 'title': 'SsODNet paper', 'year': 2022, 'bibcode': 'TBD'}
Replacing value with empty default to continue.

Error: parameters -> dynamical -> tisserand_parameter -> bibref is invalid: value is not a valid list
Passed value: {'shortbib': 'berthier+2022', 'title': 'SsODNet paper', 'year': 2022, 'bibcode': 'TBD', 'doi': 'TBD'}
Replacing value with empty default to continue.

MB>Outer
```

Maybe I missed some steps during the installation?

**Comment by maxmahlke** [comment]
I see that the errors as they are printed can be confusing, and most of the time, the user won't care if they are just exploring data on the command line. I just pushed version 1.4.18, which only prints errors on the command line if you pass the `-v` or `--verbose` flag. Could you try it out?

**Comment by ysBach** [comment]
@maxmahlke Hi! What a quick patch.
Now it works like a charm --- I checked the error message does not appear, and it is turned on when it is run with ``-v`` option.

Closing the issue :D
