### ISSUE TITLE
rocks crash with asteroid 1998 KY26

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#6]
Hi,

On my end, running `rocks spins 1998 KY26`
leads to a crash with multiple errors. Should be easy to reproduce, but let me know if you want terminal output.

**Comment by maxmahlke** [comment]
Confirmed and fixed. I'm pushing the fix to the github repo but not yet the new version to pypi as there are likely more fixes coming in a short time.

**Comment by maxmahlke** [comment]
Fixed in v1.6.0
