### ISSUE TITLE
[Bug] lru_cache behaviour for python <= 3.7

### ISSUE THREAD

**Issue by JulienPeloton** [maxmahlke/rocks#7]
The current snippet:

```python
@lru_cache
def load_mappings():
  """blah """
  pass

load_mappings()
```

will work for python 3.8 and above, but not for Python 3.7 (untested for lower versions). The reason is that the signature

```python
lru_cache(callable)
```
is only available from python 3.8+
3.7: https://docs.python.org/3.7/library/functools.html#functools.lru_cache
3.8: https://docs.python.org/3.8/library/functools.html#functools.lru_cache

To make it cross-compatible, one could specify the argument in the decorator (to its default value):

```python
@lru_cache(maxsize=128)
def load_mappings():
  """blah """
  pass

load_mappings()
```

**Comment by maxmahlke** [comment]
Merci for reporting and fixing!
