### ISSUE TITLE
Documentation bug (missing links)

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#9]
Hi,

On the front page of the Rocks documentation ( https://rocks.readthedocs.io/en/latest/ ) 
I see two missing links - the "What is the number of Didymos" and "What masses of Ceres have been published" boxes do not link to anywhere. I suppose this is because neither actually has tutorials available.

Also, "Which parameters can be abbreviated?" is listed twice in the tutorials section.

**Comment by maxmahlke** [comment]
Fixed, thanks for letting me know!
